# Generated by Django 5.2.3 on 2025-06-22 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pirce',
            new_name='price',
        ),
    ]
